project:
  type: book

book:
  title: "Data Technologies"
  subtitle: "Computational tools for working with data"
  author: "Martin Frigaard"
  date: "2023-06-07"
  chapters:
  - index.qmd
  - preface.qmd
  - intro.qmd
  - part: "Object-oriented programming"
    chapters: 
        - oop-basics.qmd
        - oop-in-r.qmd
  - part: "Functions"
    chapters:
      - fun-names.qmd
      - fun-arguments.qmd
      - fun-structure.qmd
      - fun-environments.qmd
  

bibliography: references.bib


format:
  html:
    theme: simplex
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto

