---
editor: 
  markdown: 
    wrap: sentence
---

# Welcome {.unnumbered}

To 'Data Science Technologies: A Non-Technical Guide'

## Book outline

### Introduction  {.unnumbered}

The Data Science Ecosystem

*Importance and Relevance:* The rising importance of data science and why having mental models of these technologies matters. 

*Everyday Impact:* How these technologies influence our everyday lives (social media, business, healthcare).

### Part I {.unnumbered}

Foundational Concepts in Computational Statistics

*1.1.* *Code*

Overview of common programming languages and how they're used to communicate 
with machines and humans. 

*1.2.* *Data*

Overview of data types, data sources, and how data is collected.

*1.3.* *Command Line Interface*

Introduction to CLI basics and its importance in data science.

*1.4.* *The Data Science Workflow*

Simplified explanation of the data science lifecycle from data collection to decision-making.

### Part II {.unnumbered}

Data Storage and Retrieval 

*2.1.* *Data Processing*

Common tasks for cleaning and transforming raw data.

*2.2* *Big Data*

Working with larger datasets using tools like Apache Hadoop, Spark, and SQL-based commands.

*3.3* *Data Storage*

Overview of file formats (CSV, JSON, Parquet) and database tools (SQL, NoSQL, and data lakes).

### Part III {.unnumbered}

Computational Analysis Tools

*3.1. Exploratory Data Analysis*

Leveraging visualization libraries (Matplotlib, Seaborn, ggplot2).


*3.2. Statistical Analysis with Python and R*

How to conduct descriptive and inferential analysis

*3.3. Machine Learning Libraries*

Overview of key machine learning tools (Scikit-learn, TensorFlow, Keras, 
caret).

### Part IV {.unnumbered}

Machine Learning in Practice

*4.1. Supervised Learning Algorithms*

Regression, classification, and decision trees using popular libraries.

*4.2. Unsupervised Learning Algorithms*

Clustering, dimensionality reduction, and topic modeling techniques

*4.3. Model Evaluation and Optimization*

Approaches for model selection, tuning, and validation.

### Part V {.unnumbered} 

Web Technologies 

### Part VI {.unnumbered} 

Automation and Pipelines

*6.1. Scripting and Automation*

Basics of writing data workflows with Python, Bash, and command-line tools

*6.2. Pipeline Orchestration Tools*

Airflow, Luigi, and others for managing data pipelines.

*6.3. Deployment Strategies*

Creating automated deployment workflows using Docker, Kubernetes, and 
serverless architectures.

### Part VII {.unnumbered}

Putting It All Together

*7.1. Project Templates*

Step-by-step guide to designing and developing data science projects.

*7.2.* *Case Studies and Examples*

Real-world use cases demonstrating command-based data workflows.

*7.3. Beyond the Book*

Resources for exploring data science tools further (open-source projects, 
courses, blogs).

### Conclusion {.unnumbered}

The Future of Command-Based Data Science

*Emerging Trends:* What's next in command-based data science and how it connects with the broader tech landscape.

*Practical Skills Roadmap:* How readers can continue building relevant skills and apply them to their own work.

### Appendix {.unnumbered}

A1.  Glossary of Key Terms

A2.  Supplementary References for Deep-Dive Learning
