# Introduction {.unnumbered}

> *This is a book created from markdown and executable code. See @knuth84 for additional discussion of literate programming.*

I've left the boilerplate text above in this text because it's fitting for a book on data technology. [Donald Knuth](https://en.wikipedia.org/wiki/Donald_Knuth?oldformat=true) and his contributions to [literate programming](https://en.wikipedia.org/wiki/Literate_programming?oldformat=true) eventually lead to the document you're reading. In literate programming, explanations and logic (written in natural language) are interspersed with snippets or 'chunks' of code, which can be compiled into various output formats, or used as a virtual notebook environment. 

It's hard to overstate the importance of this technology. Before literate programming, the world of code was largely separated from most other forms of written language. The combination of code with natural language...


Literate programming has done for code what... 

## Open source

I've included the steps for publishing this book *inside* the book because it's serves as an excellent example of the topics contained in this text. This book is [written in Quarto](https://quarto.org/docs/books/), which is an '*open-source scientific and technical publishing system.*' All of the tools in this text are [open-source](https://en.wikipedia.org/wiki/Open_source), which means the source code (i.e. files) to create it are '*made freely available for possible modification and redistribution*.'

If we look at the code files used to create this book in the folder tree below we notice multiple file types (extensions) and names:

```{r}
#| echo: false
#| eval: true
#| collapse: false
fs::dir_tree("_book", recurse = TRUE)
```

Each of these 

These files are stored in a [GitHub repository](https://github.com/mjfrigaard/data-tech). GitHub is a platform for hosting open source projects that use [Git](https://git-scm.com/), the world's most popular distributed version control system.

## Collaboration

Basic knowledge of Git has become somewhat necessary when you decide to enter the data technology ecosystem (or other open-source projects). I won't be diving into the Git workflow here, but I *will* cover the commands I used to store and publish this book. 

The following commands are entered at the command line (Terminal if you're using macOS).

1. I created a repository on [GitHub.com](https://github.com) like this one: [mjfrigaard/data-tech](https://github.com/mjfrigaard/data-tech) 

2. Add (`-A`) and commit (`commit -m`) the files in the book folder: 

```{verbatim}
#| eval: false
#| echo: true
#| code-fold: false
$ git add -A
$ git commit -m "first commit"
```

3. `push` local files to GitHub repo

```{verbatim}
#| eval: false
#| echo: true
#| code-fold: false
$ git remote add origin git@github.com:mjfrigaard/data-tech.git
$ git branch -M main
$ git push -u origin main
```

4. Create (checkout) an empty `gh-pages` branch

```{verbatim}
#| eval: false
#| echo: true
#| code-fold: false
$ git checkout --orphan gh-pages
Switched to a new branch 'gh-pages'
$ git reset --hard 
$ git commit --allow-empty -m "Initialising gh-pages branch"
Initialising gh-pages branch
```

5. `push` the book files to the `gh-pages` branch

```{verbatim}
#| eval: false
#| echo: true
#| code-fold: false
$ git push origin gh-pages
Enumerating objects: 2, done.
Counting objects: 100% (2/2), done.
Writing objects: 100% (2/2), 176 bytes | 176.00 KiB/s, done.
Total 2 (delta 0), reused 0 (delta 0), pack-reused 0
remote: 
remote: Create a pull request for 'gh-pages' on GitHub by visiting:
remote:      https://github.com/mjfrigaard/data-tech/pull/new/gh-pages
remote: 
To github.com:mjfrigaard/data-tech.git
 * [new branch]      gh-pages -> gh-pages
```

5. Switch (`checkout`) back to `main` branch

```{verbatim}
#| eval: false
#| echo: true
#| code-fold: false
$ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
```

6. `publish` to `gh-pages` branch

```{verbatim}
#| eval: false
#| echo: true
#| code-fold: false
$ quarto publish gh-pages
? Update site at https://mjfrigaard.github.io/data-tech/? (Y/n) 
```

```{verbatim}
#| eval: false
#| echo: true
#| code-fold: false
? Update site at https://mjfrigaard.github.io/data-tech/? (Y/n) Yes
```

